//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinikApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KlinikApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apotek_online_k24klik_201611200342221922_385_Sea_Quill_Hair_Nutrition {
            get {
                object obj = ResourceManager.GetObject("apotek_online_k24klik_201611200342221922_385-Sea-Quill-Hair-Nutrition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apotek_online_k24klik_201611200342221922_385_Sea_Quill_Hair_Nutrition1 {
            get {
                object obj = ResourceManager.GetObject("apotek_online_k24klik_201611200342221922_385-Sea-Quill-Hair-Nutrition1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apotek_online_k24klik_20201020035109359225_VITAMIN_C_IPI {
            get {
                object obj = ResourceManager.GetObject("apotek_online_k24klik_20201020035109359225_VITAMIN-C-IPI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apotek_online_k24klik_20210819021926359225_MOIST_CREAM_100G {
            get {
                object obj = ResourceManager.GetObject("apotek_online_k24klik_20210819021926359225_MOIST-CREAM-100G", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apotek_online_k24klik_20230123110239359225_MYLANTA_150_ML_1 {
            get {
                object obj = ResourceManager.GetObject("apotek_online_k24klik_20230123110239359225_MYLANTA-150-ML-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apotek_online_k24klik_20230123110239359225_MYLANTA_150_ML_1_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("apotek_online_k24klik_20230123110239359225_MYLANTA-150-ML-1-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apotek_online_k24klik_20230225113112359225_1__6_ {
            get {
                object obj = ResourceManager.GetObject("apotek_online_k24klik_20230225113112359225_1--6-", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apotek_online_k24klik_20230225113332359225_3__3_ {
            get {
                object obj = ResourceManager.GetObject("apotek_online_k24klik_20230225113332359225_3--3-", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apotek_online_k24klik_20230227113301359225_SOMETHING_PEELING_SOLUTION__F_ {
            get {
                object obj = ResourceManager.GetObject("apotek_online_k24klik_20230227113301359225_SOMETHING-PEELING-SOLUTION--F-", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apotek_online_k24klik_20230227113301359225_SOMETHING_PEELING_SOLUTION__F_1 {
            get {
                object obj = ResourceManager.GetObject("apotek_online_k24klik_20230227113301359225_SOMETHING-PEELING-SOLUTION--F-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apotek_online_k24klik_20230227113913359225_SOMETHING_GLOW_MAKER__F_ {
            get {
                object obj = ResourceManager.GetObject("apotek_online_k24klik_20230227113913359225_SOMETHING-GLOW-MAKER--F-", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apotek_online_k24klik_20230313015336359225_CERAMIC_SKIN_SAVIOUR {
            get {
                object obj = ResourceManager.GetObject("apotek_online_k24klik_20230313015336359225_CERAMIC-SKIN-SAVIOUR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apotek_online_k24klik_20230313023527359225_SCARLETT_POMEGRANTE_BRIGHTENING_SHOWER_SCRUB {
            get {
                object obj = ResourceManager.GetObject("apotek_online_k24klik_20230313023527359225_SCARLETT-POMEGRANTE-BRIGHTENING-SHOWER" +
                        "-SCRUB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apotek_online_k24klik_20230915111651359225_RENU_FOR_COLOUR {
            get {
                object obj = ResourceManager.GetObject("apotek_online_k24klik_20230915111651359225_RENU-FOR-COLOUR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apotek_online_k24klik_20250228012617359225_D3__K2_IPI_3 {
            get {
                object obj = ResourceManager.GetObject("apotek_online_k24klik_20250228012617359225_D3--K2-IPI-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap credit_card {
            get {
                object obj = ResourceManager.GetObject("credit-card", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2025_03_13_053517 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2025-03-13 053517", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap doctor {
            get {
                object obj = ResourceManager.GetObject("doctor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap doctors_office {
            get {
                object obj = ResourceManager.GetObject("doctors-office", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap medical_team {
            get {
                object obj = ResourceManager.GetObject("medical-team", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nutritionist {
            get {
                object obj = ResourceManager.GetObject("nutritionist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap registration {
            get {
                object obj = ResourceManager.GetObject("registration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap volunteer {
            get {
                object obj = ResourceManager.GetObject("volunteer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
